# Generated by Django 2.1 on 2019-01-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date_created',
        ),
    ]
