# Generated by Django 2.1 on 2019-02-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_auto_20190128_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_id',
            new_name='file_id',
        ),
    ]
